### ISSUE TITLE
[BUG]The webhook can not be verify

### ISSUE THREAD

**Issue by r06521601** [line/line-bot-sdk-nodejs#235] opened 2020-07-10 07:35 UTC
## Bug Report

**Describe the bug**
follow the guide and use ngrok to access the hook, but always can not be verify. I'm pretty sure I used the following code and work fine before, but it does't work now. I also check the ngrok can access the /hello route. 

**To Reproduce**
```node
const express = require('express');
const line = require('@line/bot-sdk');
const bodyParser = require('body-parser');

const app = express();

const config = {
    channelAccessToken: "",
    channelSecret: ""
};

const client = new line.Client(config);

app.use('/webhook', line.middleware(config));
app.use(bodyParser.json());

app.get("/hello", (req, res)=>{
    res.send("go!")
})

app.post("/webhook", (req, res) => {
    Promise.all(req.body.events.map(handleEvent))
      .then(result => res.json(result))
      .catch(err => {
        console.error("error at app.post", err);
      });
  });

function handleEvent(event) {

    console.log(event);
    if (event.type === 'message' && event.message.type === 'text') {
        handleMessageEvent(event);
    } else {
        return Promise.resolve(null);
    }
}

function handleMessageEvent(event) {
    // code
}

app.set('port', (process.env.PORT || 3000));

app.listen(app.get('port'), function () {
    console.log('run at port', app.get('port'));
});
```

**Expected behavior**
verify the webhook

**Environment (please complete the following information):**
 - OS: macOS 10.15.4
 - Node.js Version: 14.5.0
 - line-bot-sdk-nodejs version(s): 6.14.5

Thanks for your helping~

**Comment by xingoxu** [comment] 2020-07-10 08:12
Hello,
I've tried the same code as yours and it runs well.

![image](https://user-images.githubusercontent.com/8542907/87131778-dc675600-c2cf-11ea-88c7-2182be1dd7b5.png)

I'm using `line-bot-sdk-nodejs`@7 though there's no change on auth between 6.14.5 and 7 but would you please try it again?

**Comment by r06521601** [comment] 2020-07-10 08:48
Thanks you for reply so quickly!

I tried run on repl.it, and it verify work!

but ngrok doesn't work, I am not sure what going on ngrok. at least find the problem ~

**Comment by xingoxu** [comment] 2020-07-10 08:50
Since it's not a bug and you've confirmed, I will close this for you.

**Closed by xingoxu** 2020-07-10 08:50 UTC
Labels: bug
